In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'framingham.csv')
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [4]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [5]:
# Drop columns that are not use
df = df.drop(columns = ['education', 'currentSmoker', 'BPMeds', 'prevalentStroke', 'prevalentHyp', 'diabetes', 'diaBP', 'BMI'], axis = 1)

In [6]:
df.head()

   male  age  cigsPerDay  totChol  sysBP  heartRate  glucose  TenYearCHD
0     1   39         0.0    195.0  106.0       80.0     77.0           0
1     0   46         0.0    250.0  121.0       95.0     76.0           0
2     1   48        20.0    245.0  127.5       75.0     70.0           0
3     0   61        30.0    225.0  150.0       65.0    103.0           1
4     0   46        23.0    285.0  130.0       85.0     85.0           0

In [7]:
df.isnull().sum()

male            0
age             0
cigsPerDay     29
totChol        50
sysBP           0
heartRate       1
glucose       388
TenYearCHD      0
dtype: int64

In [8]:
df.rename(columns = {'male' : 'sex'}, inplace = True)

In [9]:
df.head()

   sex  age  cigsPerDay  totChol  sysBP  heartRate  glucose  TenYearCHD
0    1   39         0.0    195.0  106.0       80.0     77.0           0
1    0   46         0.0    250.0  121.0       95.0     76.0           0
2    1   48        20.0    245.0  127.5       75.0     70.0           0
3    0   61        30.0    225.0  150.0       65.0    103.0           1
4    0   46        23.0    285.0  130.0       85.0     85.0           0

In [10]:
df.dropna(inplace = True)

In [11]:
df.isnull().sum()

sex           0
age           0
cigsPerDay    0
totChol       0
sysBP         0
heartRate     0
glucose       0
TenYearCHD    0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3816 entries, 0 to 4239
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sex         3816 non-null   int64
 1   age         3816 non-null   int64
 2   cigsPerDay  3816 non-null   float64
 3   totChol     3816 non-null   float64
 4   sysBP       3816 non-null   float64
 5   heartRate   3816 non-null   float64
 6   glucose     3816 non-null   float64
 7   TenYearCHD  3816 non-null   int64
dtypes: float64(5), int64(3)
memory usage: 268.3 KB

In [35]:
df['TenYearCHD'].value_counts()

TenYearCHD
0    3226
1     590
Name: count, dtype: int64

In [36]:
x = df.drop(columns = ['TenYearCHD'], axis = 1)
y = df['TenYearCHD']

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42, stratify = y)

In [39]:
from imblearn.over_sampling import SMOTE

In [40]:
smote = SMOTE()

In [41]:
x_train, y_train = smote.fit_resample(x_train, y_train)

In [42]:
x_train.shape, x_test.shape

((5160, 7), (764, 7))

In [43]:
y_train.shape, y_test.shape

((5160,), (764,))

In [44]:
print(y_train.value_counts())
print(y_test.value_counts())

TenYearCHD
1    2580
0    2580
Name: count, dtype: int64
TenYearCHD
0    646
1    118
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
scaler = MinMaxScaler()

In [25]:
x_train_scaling = scaler.fit_transform(x_train)
x_test_scaling = scaler.transform(x_test)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
from sklearn.model_selection import GridSearchCV

In [27]:
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score

In [28]:
models_params = {

    "Logistic Regression": (
        LogisticRegression(random_state=42, max_iter=1000),
        {
            "C": [0.01, 0.1, 1, 10, 100],
            "penalty": ["l1", "l2"],
            "solver": ["liblinear"],
            "class_weight": [None, "balanced"]
        }
    ),


    "SVC": (
        SVC(probability=True, random_state=42),
        {
            "C": [0.1, 1],
            "kernel": ["linear", "sigmoid"],
            "gamma": ["scale", "auto"],
            "class_weight": [None, "balanced"]
        }
    ),


    "Decision Tree": (
        DecisionTreeClassifier(random_state=42),
        {
            "criterion": ["gini", "entropy", "log_loss"],
            "max_depth": [3, 5, 8, 10, 15, None],
            "min_samples_split": [2, 5, 10],
            "min_samples_leaf": [1, 2, 4],
            "max_features": [None, "sqrt", "log2"]
        }
    ),


    "Random Forest": (
        RandomForestClassifier(random_state=42),
        {
            "n_estimators": [100, 200],
            "criterion": ["gini", "entropy"],
            "max_depth": [5, 10],
            "min_samples_split": [2, 5],
            "min_samples_leaf": [1, 2],
            "max_features": ["sqrt", "log2"],
            "class_weight": [None, "balanced"]
        }
    ),


    "AdaBoost": (
        AdaBoostClassifier(random_state=42),
        {
            "n_estimators": [50, 100],
            "learning_rate": [0.01, 0.05]
        }
    ),


    "Extra Trees": (
        ExtraTreesClassifier(random_state=42),
        {
            "n_estimators": [100, 200],
            "criterion": ["gini", "entropy"],
            "max_depth": [5, 10],
            "min_samples_split": [2, 5],
            "min_samples_leaf": [1, 2],
            "max_features": ["sqrt", "log2"]
        }
    ),


    "KNN": (
        KNeighborsClassifier(),
        {
            "n_neighbors": [3,5],
            "weights": ["uniform", "distance"],
            "metric": ["euclidean", "manhattan"],
            "p": [1,2]
        }
    ),


    "Bernoulli NB": (
        BernoulliNB(),
        {
            "alpha": [0.1,0.5,1,2]
        }
    ),


    "Multinomial NB": (
        MultinomialNB(),
        {
            "alpha": [0.1,0.5,1,2]
        }
    ),


    "Gaussian NB": (
        GaussianNB(),
        {
            "var_smoothing": [1e-9,1e-8,1e-7,1e-6]
        }
    )
}

In [33]:
results = []

for name, (model, params) in models_params.items():

    grid_search = GridSearchCV(
        estimator = model,
        param_grid = params,
        cv = 5,
        n_jobs = -1,
        scoring = 'recall'
    )

    grid_search.fit(x_train_scaling, y_train)

    y_pred = grid_search.predict(x_test_scaling)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred)

    results.append({
        "Model": name,
        "Accuracy": round(accuracy, 4),
        "Precision": round(precision, 4),
        "Recall": round(recall, 4),
        "F1 Score": round(f1, 4),
        "ROC AUC": round(roc_auc, 4),
        # "Best Parameters": grid_search.best_params_,
        "CV Accuracy": round(grid_search.best_score_, 4)
    })

    print("=" * 60)
    print("Model :", name)
    print("=" * 60)
    print(classification_report(y_test, y_pred))
    print("Best Parameters :", grid_search.best_params_)
    print("Best CV Score :", round(grid_search.best_score_, 4))
    print()

summary_df = pd.DataFrame(results)

summary_df = summary_df.sort_values(
    by = "Recall",
    ascending = False
).reset_index(drop=True)

summary_df.index = summary_df.index + 1

print("=" * 100)
print("MODEL COMPARISON SUMMARY")
print("=" * 100)

print(summary_df)

============================================================
Model : Logistic Regression
============================================================
              precision    recall  f1-score   support

           0       0.89      0.42      0.57       646
           1       0.18      0.70      0.29       118

    accuracy                           0.46       764
   macro avg       0.53      0.56      0.43       764
weighted avg       0.78      0.46      0.53       764

Best Parameters : {'C': 0.01, 'class_weight': None, 'penalty': 'l1', 'solver': 'liblinear'}
Best CV Score : 0.9395

============================================================
Model : SVC
============================================================
              precision    recall  f1-score   support

           0       0.90      0.65      0.75       646
           1       0.23      0.58      0.33       118

    accuracy                           0.64       764
   macro avg       0.56      0.62      0.54       764
weighted avg       0.79      0.64      0.69       764

Best Parameters : {'C': 0.1, 'class_weight': None, 'gamma': 'scale', 'kernel': 'linear'}
Best CV Score : 0.6981

============================================================
Model : Decision Tree
============================================================
              precision    recall  f1-score   support

           0       0.86      0.77      0.81       646
           1       0.20      0.32      0.25       118

    accuracy                           0.70       764
   macro avg       0.53      0.55      0.53       764
weighted avg       0.76      0.70      0.73       764

Best Parameters : {'criterion': 'gini', 'max_depth': 15, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best CV Score : 0.8132

============================================================
Model : Random Forest
============================================================
              precision    recall  f1-score   support

           0       0.89      0.74      0.80       646
           1       0.25      0.49      0.33       118

    accuracy                           0.70       764
   macro avg       0.57      0.61      0.57       764
weighted avg       0.79      0.70      0.73       764

Best Parameters : {'class_weight': None, 'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best CV Score : 0.8469

============================================================
Model : AdaBoost
============================================================
              precision    recall  f1-score   support

           0       0.90      0.50      0.64       646
           1       0.20      0.69      0.31       118

    accuracy                           0.53       764
   macro avg       0.55      0.60      0.48       764
weighted avg       0.79      0.53      0.59       764

Best Parameters : {'learning_rate': 0.01, 'n_estimators': 100}
Best CV Score : 0.819

============================================================
Model : Extra Trees
============================================================
              precision    recall  f1-score   support

           0       0.89      0.67      0.76       646
           1       0.23      0.54      0.32       118

    accuracy                           0.65       764
   macro avg       0.56      0.60      0.54       764
weighted avg       0.79      0.65      0.69       764

Best Parameters : {'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Best CV Score : 0.7694

============================================================
Model : KNN
============================================================
              precision    recall  f1-score   support

           0       0.87      0.69      0.77       646
           1       0.20      0.43      0.28       118

    accuracy                           0.65       764
   macro avg       0.54      0.56      0.52       764
weighted avg       0.77      0.65      0.69       764

Best Parameters : {'metric': 'manhattan', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'}
Best CV Score : 0.9248

============================================================
Model : Bernoulli NB
============================================================
              precision    recall  f1-score   support

           0       0.87      0.50      0.64       646
           1       0.18      0.58      0.27       118

    accuracy                           0.52       764
   macro avg       0.52      0.54      0.45       764
weighted avg       0.76      0.52      0.58       764

Best Parameters : {'alpha': 0.1}
Best CV Score : 0.5167

============================================================
Model : Multinomial NB
============================================================
              precision    recall  f1-score   support

           0       0.79      0.41      0.54       646
           1       0.11      0.41      0.18       118

    accuracy                           0.41       764
   macro avg       0.45      0.41      0.36       764
weighted avg       0.69      0.41      0.49       764

Best Parameters : {'alpha': 0.1}
Best CV Score : 0.6438

============================================================
Model : Gaussian NB
============================================================
              precision    recall  f1-score   support

           0       0.88      0.78      0.83       646
           1       0.26      0.42      0.32       118

    accuracy                           0.73       764
   macro avg       0.57      0.60      0.58       764
weighted avg       0.79      0.73      0.75       764

Best Parameters : {'var_smoothing': 1e-09}
Best CV Score : 0.4554

====================================================================================================
MODEL COMPARISON SUMMARY
====================================================================================================
                  Model  Accuracy  Precision  Recall  F1 Score  ROC AUC  \
1   Logistic Regression    0.4647     0.1816  0.7034    0.2887   0.5622
2              AdaBoost    0.5275     0.2015  0.6949    0.3124   0.5959
3                   SVC    0.6374     0.2323  0.5847    0.3325   0.6159
4          Bernoulli NB    0.5157     0.1769  0.5847    0.2717   0.5439
5           Extra Trees    0.6479     0.2294  0.5424    0.3224   0.6048
6         Random Forest    0.6976     0.2533  0.4915    0.3343   0.6134
7                   KNN    0.6518     0.2040  0.4322    0.2772   0.5621
8           Gaussian NB    0.7251     0.2604  0.4237    0.3226   0.6020
9        Multinomial NB    0.4136     0.1127  0.4068    0.1765   0.4108
10        Decision Tree    0.7003     0.2032  0.3220    0.2492   0.5457

    CV Accuracy
1        0.9395
2        0.8190
3        0.6981
4        0.5167
5        0.7694
6        0.8469
7        0.9248
8        0.4554
9        0.6438
10       0.8132

In [50]:
import pickle

In [71]:
final_model = LogisticRegression(
    C=0.01,
    penalty="l1",
    solver="liblinear",
    random_state=42,
    max_iter=1000
)

final_model.fit(x_train_scaling, y_train)

with open('heart_disease_model.pkl', 'wb') as file:
    pickle.dump(final_model, file)

In [52]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)