In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'Salary_Data.csv')
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [4]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [5]:
x = df.drop(columns = ['Salary'], axis = 1)
y = df['Salary']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [8]:
x_train.shape, x_test.shape

((24, 1), (6, 1))

In [9]:
y_train.shape, y_test.shape

((24,), (6,))

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [11]:
lr = LinearRegression()
rfr = RandomForestRegressor(n_estimators = 50, max_depth = 10)
adr = AdaBoostRegressor()
etr = ExtraTreesRegressor(n_estimators = 50, max_depth = 10)
gbr = GradientBoostingRegressor()
dcr = DecisionTreeRegressor()
knr = KNeighborsRegressor(n_neighbors = 5)
svr = SVR()

In [27]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [36]:
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.9771826321808226
Mean Absolute Error:  2891.1815035992827
Mean Squared Error:  14816794.904780814
Root Mean Squared Error:  3849.2590072351345

In [29]:
rfr.fit(x_train, y_train)
y_pred = rfr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.961540621706424
Mean Absolute Error:  4604.271666666665
Mean Squared Error:  24974165.506608322
Root Mean Squared Error:  4997.415882894711

In [30]:
adr.fit(x_train, y_train)
y_pred = adr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.9403924444884284
Mean Absolute Error:  4824.5
Mean Squared Error:  38707046.833333336
Root Mean Squared Error:  6221.498761016781

In [31]:
etr.fit(x_train, y_train)
y_pred = etr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.9385480353776228
Mean Absolute Error:  5477.514999999999
Mean Squared Error:  39904741.13934999
Root Mean Squared Error:  6317.019957175217

In [32]:
gbr.fit(x_train, y_train)
y_pred = gbr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.93292126875718
Mean Absolute Error:  5287.030739978983
Mean Squared Error:  43558565.17606018
Root Mean Squared Error:  6599.8913003215575

In [33]:
dcr.fit(x_train, y_train)
y_pred = dcr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.9320293285793841
Mean Absolute Error:  5336.083333333333
Mean Squared Error:  44137759.708333336
Root Mean Squared Error:  6643.625494286484

In [34]:
knr.fit(x_train, y_train)
y_pred = knr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  0.9399853520439626
Mean Absolute Error:  5554.366666666666
Mean Squared Error:  38971398.326666646
Root Mean Squared Error:  6242.707611819302

In [35]:
svr.fit(x_train, y_train)
y_pred = svr.predict(x_test)

print('R2 Score: ', r2_score(y_test, y_pred))
print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error: ', mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error: ', root_mean_squared_error(y_test, y_pred))

R2 Score:  -0.3409250492048561
Mean Absolute Error:  22515.31352320938
Mean Squared Error:  870749491.9748253
Root Mean Squared Error:  29508.4647512341

In [37]:
import pickle

In [40]:
with open('salary.pkl', 'wb') as file:
    pickle.dump(lr, file)
print('Model Saved!!')

Model Saved!!